### ISSUE TITLE
updater not working in powershell

### ISSUE THREAD

**Issue by AnthonySlay3r** [FeralAI/vsFIGHTER-Firmware#2]
I ran the updater but it keeps saying it does not recognize the update.ps1 because of the extension, both in PowerShell and command prompt, after the initial reset into bootloader.

**Comment by FeralAI** [comment]
I have work in progress installer I can post that may help. Give me a few
hours to get it all together.

**Comment by FeralAI** [comment]
In theory the powershell should work if it has permissions, but it is a little flaky.

I have added a new installer zip package to the release, here is the link: https://github.com/FeralAI/vsFIGHTER-Firmware/releases/download/v1.0.2/vsFIGHTER-Firmware_v1.0.2-NewInstaller.zip

Please test that out by extracting the contents, then running the `TUFUpdater.exe`. You will get a command prompt asking you to double press the reset button. It should detect the controller and automatically perform the update. If you have issues please copy the output from the window and/or screenshot it and post here.

**Comment by AnthonySlay3r** [comment]
Thank you so much for your help. The update was successful this time. I own both of your vsfighter controller and both updated just fine.

**Comment by FeralAI** [comment]
Awesome! I've replaced the current release zip with the new installer and added instructions. This will be used going forward. Closing this issue.
